"""
Module chứa mapping từ teencode sang từ chuẩn.
"""
# teen-code mapping (mở rộng với các từ chửi thề)
TEENCODE = {
    "ko": "không",
    "k": "không",
    "khong": "không",
    "hok": "không",
    "dc": "được",
    "đc": "được",
    "mik": "mình",
    "mk": "mình",
    "mn": "mọi người",
    "thik": "thích",
    "iu": "yêu",
    # Các từ chửi thề (để normalize)
    # Các từ chửi thề, nói tục, viết tắt, biến thể phổ biến (100+)
    "vcl": "chửi",
    "vl": "chửi",
    "vãi": "chửi",
    "vc": "chửi",
    "vcd": "chửi",
    "vđ": "chửi",
    "vcc": "chửi",
    "vcll": "chửi",
    "vcll": "chửi",
    "vnc": "chửi",
    "vđc": "chửi",
    "vll": "chửi",
    "đm": "chửi",
    "đmm": "chửi",
    "đmmm": "chửi",
    "đmẹ": "chửi",
    "dm": "chửi",
    "dmm": "chửi",
    "dmmm": "chửi",
    "d4m": "chửi",
    "dcm": "chửi",
    "dcmn": "chửi",
    "dcmm": "chửi",
    "cl": "chửi",
    "clm": "chửi",
    "clmm": "chửi",
    "clmn": "chửi",
    "cmm": "chửi",
    "cmn": "chửi",
    "cmmn": "chửi",
    "cái lồn": "chửi",
    "cailon": "chửi",
    "cờ lờ": "chửi",
    "cc": "chửi",
    "ccc": "chửi",
    "ccm": "chửi",
    "ccl": "chửi",
    "cđ": "chửi",
    "cđmm": "chửi",
    "cđmmn": "chửi",
    "l": "chửi",
    "ll": "chửi",
    "lồn": "chửi",
    "lon": "chửi",
    "loz": "chửi",
    "lmao": "chửi",
    "má mày": "chửi",
    "mả mày": "chửi",
    "máu chó": "chửi",
    "mịa": "chửi",
    "mịe": "chửi",
    "móa": "chửi",
    "mẹ mày": "chửi",
    "mm": "chửi",
    "mml": "chửi",
    "mmlm": "chửi",
    "mmmay": "chửi",
    "vú": "chửi",
    "bú": "chửi",
    "bú m": "chửi",
    "bú mẹ": "chửi",
    "bú l": "chửi",
    "đụ": "chửi",
    "đjt": "chửi",
    "dit": "chửi",
    "địt": "chửi",
    "djt": "chửi",
    "djmm": "chửi",
    "quần què": "chửi",
    "qq": "chửi",
    "oq": "chửi",
    "đéo": "chửi",
    "deo": "chửi",
    "đéo hiểu": "chửi",
    "éo": "chửi",
    "éo biết": "chửi",
    "dkm": "chửi",
    "dcm": "chửi",
    "fuck": "chửi",
    "fck": "chửi",
    "f*ck": "chửi",
    "f***": "chửi",
    "shit": "chửi",
    "shjt": "chửi",
    "sh*t": "chửi",
    "sh!t": "chửi",
    "đách": "chửi",
    "dk": "chửi",
    "dkmm": "chửi",
    "dmmk": "chửi",
    "đkm": "chửi",
    "dkm": "chửi",
    "dkmn": "chửi",
    "đkmm": "chửi",
    "đkmn": "chửi",
    "ncc": "chửi",
    "bố láo": "chửi",
    "bố mày": "chửi",
    "bà mày": "chửi",
    "bà nội mày": "chửi",
    "bà nó": "chửi",
    "cu": "chửi",
    "cặc": "chửi",
    "cak": "chửi",
    "cac": "chửi",
    "kặc": "chửi",
    "kồn": "chửi",
    "cđ": "chửi",
    "bitch": "chửi",
    "b!tch": "chửi",
    "bít": "chửi",
    "bịt": "chửi",
    "bsv": "chửi",
    "ngu": "chửi",
    "đần": "chửi",
    "óc chó": "chửi",
    "oc cho": "chửi",
    "ocdog": "chửi",
    "oc": "chửi",
    "óc": "chửi",
    "occho": "chửi",
    "lol": "chửi",
    "đú": "chửi"
}

